controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false

    # 피드백 없는 PWM 서보를 사용할 때 우선 적용
    open_loop_control: true

    # trajectory 마지막 지점에서 속도가 0이 되도록 요구. 애매한데.
    allow_nonzero_velocity_at_trajectory_end: false